dist: trusty
sudo: false
language: python
cache: pip
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -U pip
  - pip -q install -r requirements.txt
  - pip install -e .

  # dev dependencies
  - pip install flake8
  - pip install coverage

# syntax and style checks before tests get executed
before_script:
  # Syntax Checks
  # stop the build if there are Python syntax errors or undefined names
  - time flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - time flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

script:
  # Unit test
  - python -m unittest discover -v
  - coverage run -m unittest discover
  - coverage report --skip-covered --omit '*/virtualenv/*'

  # Integration test
  - sh integration_test.sh 
